type of Machine Learning: 
supervised and unsupervised learning

supervised:
classification, put things into different groups 
regression, predict future numbers

unsupervised;
clustering is unsupervised, removes bias from data science 
dimension reduction 

In [1]:
import pandas as pd


In [11]:
df=pd.read_csv('imports-85 (1).data', header=None)
df.columns=['symboling','normalized-losses','make:','fuel-type:','aspiration:','num-of-doors:','body-style:','drive-wheels:','engine-location:','wheel-base:','length:','width:','height:','curb-weight:','engine-type:','num-of-cylinders:','engine-size:','fuel-system:','bore:','stroke:','compression-ratio:','horsepower:','peak-rpm:','city-mpg:','highway-mpg:','price:']
df

symboling normalized-losses        make: fuel-type: aspiration:  \
0            3                 ?  alfa-romero        gas         std   
1            3                 ?  alfa-romero        gas         std   
2            1                 ?  alfa-romero        gas         std   
3            2               164         audi        gas         std   
4            2               164         audi        gas         std   
..         ...               ...          ...        ...         ...   
200         -1                95        volvo        gas         std   
201         -1                95        volvo        gas       turbo   
202         -1                95        volvo        gas         std   
203         -1                95        volvo     diesel       turbo   
204         -1                95        volvo        gas       turbo   

    num-of-doors:  body-style: drive-wheels: engine-location:  wheel-base:  \
0             two  convertible           rwd            front         88.6   
1             two  convertible           rwd            front         88.6   
2             two    hatchback           rwd            front         94.5   
3            four        sedan           fwd            front         99.8   
4            four        sedan           4wd            front         99.4   
..            ...          ...           ...              ...          ...   
200          four        sedan           rwd            front        109.1   
201          four        sedan           rwd            front        109.1   
202          four        sedan           rwd            front        109.1   
203          four        sedan           rwd            front        109.1   
204          four        sedan           rwd            front        109.1   

     ...  engine-size:  fuel-system:  bore:  stroke: compression-ratio:  \
0    ...           130          mpfi   3.47     2.68                9.0   
1    ...           130          mpfi   3.47     2.68                9.0   
2    ...           152          mpfi   2.68     3.47                9.0   
3    ...           109          mpfi   3.19     3.40               10.0   
4    ...           136          mpfi   3.19     3.40                8.0   
..   ...           ...           ...    ...      ...                ...   
200  ...           141          mpfi   3.78     3.15                9.5   
201  ...           141          mpfi   3.78     3.15                8.7   
202  ...           173          mpfi   3.58     2.87                8.8   
203  ...           145           idi   3.01     3.40               23.0   
204  ...           141          mpfi   3.78     3.15                9.5   

    horsepower:  peak-rpm: city-mpg: highway-mpg: price:  
0           111       5000        21           27  13495  
1           111       5000        21           27  16500  
2           154       5000        19           26  16500  
3           102       5500        24           30  13950  
4           115       5500        18           22  17450  
..          ...        ...       ...          ...    ...  
200         114       5400        23           28  16845  
201         160       5300        19           25  19045  
202         134       5500        18           23  21485  
203         106       4800        26           27  22470  
204         114       5400        19           25  22625  

[205 rows x 26 columns]

try and predict price of car, since number will be a regression problem

In [16]:
df['price_clean'] = pd.to_numeric(df['price:'], errors='coerce')


In [17]:
df.dropna(subset=['price_clean'], inplace=True)

add columns to see the one with most influence: forward selections

for correlation:
df.corr()

In [22]:
abs(df.corr()['price_clean'].sort_values(ascending=False))

price_clean           1.000000
engine-size:          0.872335
curb-weight:          0.834415
width:                0.751265
length:               0.690628
wheel-base:           0.584642
height:               0.135486
compression-ratio:    0.071107
symboling             0.082391
city-mpg:             0.686571
highway-mpg:          0.704692
Name: price_clean, dtype: float64

to find slope, use scipy

In [23]:
from scipy import stats

In [54]:
linear_regression=stats.linregress(df['engine-size:'], df['price_clean'])

y=166.8600156914162(engine_size)-7963.338906281075

In [36]:
engine= int(input('please enter an engine size'))

price=(166.8600156914162*(engine))-7963.338906281075

print(" At that engine size, your price of car is estimated to be", price)


 At that engine size, your price of car is estimated to be 13728.463133603032


In [40]:
def price_engine_size(engine_size):
    price=(166.8600156914162*(engine_size))-7963.338906281075

print(price)

13728.463133603032


In [48]:
def price_call(engine_size):
    price=engine_size * linear_regression.slope + linear_regression.intercept
    return price

In [55]:
df['predicted_price'] = price_call(df['engine-size:'])
df

symboling normalized-losses        make: fuel-type: aspiration:  \
0            3                 ?  alfa-romero        gas         std   
1            3                 ?  alfa-romero        gas         std   
2            1                 ?  alfa-romero        gas         std   
3            2               164         audi        gas         std   
4            2               164         audi        gas         std   
..         ...               ...          ...        ...         ...   
200         -1                95        volvo        gas         std   
201         -1                95        volvo        gas       turbo   
202         -1                95        volvo        gas         std   
203         -1                95        volvo     diesel       turbo   
204         -1                95        volvo        gas       turbo   

    num-of-doors:  body-style: drive-wheels: engine-location:  wheel-base:  \
0             two  convertible           rwd            front         88.6   
1             two  convertible           rwd            front         88.6   
2             two    hatchback           rwd            front         94.5   
3            four        sedan           fwd            front         99.8   
4            four        sedan           4wd            front         99.4   
..            ...          ...           ...              ...          ...   
200          four        sedan           rwd            front        109.1   
201          four        sedan           rwd            front        109.1   
202          four        sedan           rwd            front        109.1   
203          four        sedan           rwd            front        109.1   
204          four        sedan           rwd            front        109.1   

     ...  bore:  stroke:  compression-ratio:  horsepower: peak-rpm: city-mpg:  \
0    ...   3.47     2.68                 9.0          111      5000        21   
1    ...   3.47     2.68                 9.0          111      5000        21   
2    ...   2.68     3.47                 9.0          154      5000        19   
3    ...   3.19     3.40                10.0          102      5500        24   
4    ...   3.19     3.40                 8.0          115      5500        18   
..   ...    ...      ...                 ...          ...       ...       ...   
200  ...   3.78     3.15                 9.5          114      5400        23   
201  ...   3.78     3.15                 8.7          160      5300        19   
202  ...   3.58     2.87                 8.8          134      5500        18   
203  ...   3.01     3.40                23.0          106      4800        26   
204  ...   3.78     3.15                 9.5          114      5400        19   

     highway-mpg: price: price_clean predicted_price  
0              27  13495     13495.0    13728.463134  
1              27  16500     16500.0    13728.463134  
2              26  16500     16500.0    17399.383479  
3              30  13950     13950.0    10224.402804  
4              22  17450     17450.0    14729.623228  
..            ...    ...         ...             ...  
200            28  16845     16845.0    15563.923306  
201            25  19045     19045.0    15563.923306  
202            23  21485     21485.0    20903.443808  
203            27  22470     22470.0    16231.363369  
204            25  22625     22625.0    15563.923306  

[201 rows x 28 columns]

In [56]:
df['diff'] = df.price_clean-df.predicted_price

In [60]:
import numpy as py

In [62]:
df['square_diff'] = py.square(df['diff'])

In [65]:
sum(df.square_diff)

3019246331.0600004

In [63]:
df.columns

Index(['symboling', 'normalized-losses', 'make:', 'fuel-type:', 'aspiration:',
       'num-of-doors:', 'body-style:', 'drive-wheels:', 'engine-location:',
       'wheel-base:', 'length:', 'width:', 'height:', 'curb-weight:',
       'engine-type:', 'num-of-cylinders:', 'engine-size:', 'fuel-system:',
       'bore:', 'stroke:', 'compression-ratio:', 'horsepower:', 'peak-rpm:',
       'city-mpg:', 'highway-mpg:', 'price:', 'price_clean', 'predicted_price',
       'diff', 'square_diff'],
      dtype='object')

for house data set, find most correlated oclumn and buidl something similar to todays for it

how off are you on average price

sklearn is machine learning for python, has most algorithms built in

In [66]:
from sklearn.linear_model import LinearRegression

In [80]:
x = df[['engine-size:', 'curb-weight:']]
y = df[['price_clean']]

In [83]:
l = LinearRegression()

In [84]:
l.fit(x,y)

LinearRegression()

In [86]:
l.predict([[130, 2548]])

/Users/hannahgraham/Library/Python/3.8/lib/python/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[13518.46048363]])

In [87]:
l.intercept_

array([-14229.71725263])

In [88]:
l.coef_

array([[112.30795761,   5.16018181]])